### ISSUE TITLE
Icon URL no longer working?

### ISSUE THREAD

**Issue by ElXando** [andrea-magni/SlackDriver#2]
As of July 18th, all our slack messages sent using SDriver no longer have an Icon URL anymore. Icon Emoji still works and Slack don't seem to have changed their API, but no matter how we add Icon_URL to the IMessage, it never comes through to Slack.

Thanks!

**Comment by ElXando** [comment]
Figured it out. Slack changed the API so if an icon_emoji is passed in, even if blank, the icon_url is no longer used. Just added:
`if FIcon_Emoji <> then`
before the Result.AddPair('icon_emoji' line.

**Comment by epachsoft** [comment]
Thank you for the comment.  I was having the same issue and I couldnt realize why.
