### ISSUE TITLE
Server certificate invalid or not present 

### ISSUE THREAD

**Issue by JosephLeon13** [andrea-magni/SlackDriver#3]
Hi,
We are using the SDriver for Delphi 10.2 Tokyo and it has been working amazingly.
We have received this message from Slack:
On March 4, 2020, Slack will end support for TLS (Transport Layer Security) versions 1.0 and 1.1, in compliance with industry best practices for security and data integrity. If you have not upgraded to TLS 1.2, requests sent to any Slack service will fail. 
Now, the messages sent to Slack fail with the following message: server certificate invalid or not present
Do you have any suggestions on how to get around this?  Is this some kind of configuration issue or does it require a code change?
Any help would be appreciated.

**Comment by epachsoft** [comment]
SDriver uses TNetHttpClient, so it basically works with the http client software that the underlying OS has.  If I recall correctly, sometimes it will just work depending on the OS you are, e.g. windows 2012 server, otherwise, there is an option to enable the Secure protocols you want to use on the component itself.

**Comment by ElXando** [comment]
As epachsoft said you can enable the secure protocols you want to use, which I've had to do as when running from some places it doesn't seem to choose the correct version.

I simply added this line:

`TheClient.SecureProtocols := [THTTPSecureProtocol.TLS12];`

after the line

`TheClient := TNetHTTPClient.Create(nil);`

in SDriver.Executor.

**Comment by JosephLeon13** [comment]
I installed this patch on the server.  This is how I fixed the Slack Certificate Error: 

https://support.microsoft.com/en-au/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi
